### ISSUE TITLE
Publish jinja2_webpack seperately

### ISSUE THREAD

**Issue by JDeuce** [stevearc/pyramid_webpack#2]
Hi would you consider publishing the jinja2 extension separately with less dependencies for use outside of pyramid?

**Comment by stevearc** [comment]
That might be tricky since the jinja2 extension requires specific methods on the request object. What web framework would you want to use this with?

**Comment by JDeuce** [comment]
I would want to use it without any web framework.

We have some scripts now that use the jinja2 webassets extension to statically render a jinja2 template to a flat HTML file with code that more or less looks like this:

```python
import jinja2
from webassets.loaders import YAMLLoader as AssetsLoader

web_assets_file = 'webassets.yaml'
template_directory = '.'
template_name = 'test.jinja2'
template_dict = {}
output_file = open('out.html', 'w')

jinja2_env = jinja2.Environment(
    loader=jinja2.FileSystemLoader(template_directory, encoding='utf-8'),
    extensions=['webassets.ext.jinja2.AssetsExtension'])

assets_env = AssetsLoader(web_assets_file).load_environment()
jinja2_env.assets_environment = assets_env

template = jinja2_env.get_template(template_name)
render = template.render(template_dict)

output_file.write(render.encode('utf-8'))
```

And we want to start using webpack instead of webassets.

For webassets all the extension really does is read the webassets manifest file to map which file goes with which bundle.

And so that's the part we would want to see potentially peeled off of this project, like where it can read the stats.json file to map which files goes to which bundle.

So some kind of API like this would be useful to me:

```python
import jinja2
from webpack_jinja2 import WebpackState, WebpackExtension

stats_file = 'webpack-stats.json'
template_directory = '.'
template_name = 'test.jinja2'
template_dict = {}
output_file = open('out.html', 'w')

jinja2_env = jinja2.Environment(
    loader=jinja2.FileSystemLoader(template_directory, encoding='utf-8'),
    extensions=[WebpackExtension])

webpack_state = WebpackState(stats_file)
jinja2_env.webpack_state = webpack_state

template = jinja2_env.get_template(template_name)
render = template.render(template_dict)

output_file.write(render.encode('utf-8'))
```

**Comment by stevearc** [comment]
I seeeeee. This should definitely be possible; I'll have to look into the best way to remove the reliance upon the request object. Will begin investigating soon.

**Comment by JDeuce** [comment]
I went ahead and published https://github.com/JDeuce/python-jinja2-webpack which does what I needed.

It does not use anything from this project.

There is also https://github.com/JDeuce/python-pyramid-jinja2-webpack which is the pyramid integration of the framework agnostic jinja2 integration.
