### ISSUE TITLE
Provide a "Hello world" example/template of a pyramid project including pyramid_webpack.

### ISSUE THREAD

**Issue by eddyekofo94** [stevearc/pyramid_webpack#3]
Hi there,
I like this library, but why not provide an example, like a "HelloWorld" boilerplate fully working. something like [](this https://github.com/rokups/hello-vue-django)
I keep getting this error:

```
File "/env/lib/python3.5/site-packages/pyramid_webpack/__init__.py", line 143, in _load_stats
    "webpack-bundle-tracker plugin" .format(self.stats_file))
OSError: Could not read stats file Resource('my_project:webpack/stats.json'). Make sure you are using the webpack-bundle-tracker plugin
```
I have tried to get it working the past few days and I still can't get it to work.

**Comment by stevearc** [comment]
There is now a [cookiecutter](https://github.com/stevearc/pyramid-cookiecutter-webpack) that should make it much easier to get a basic app up and running
