### ISSUE TITLE
Issue with jinja2 rendering

### ISSUE THREAD

**Issue by amoliski** [stevearc/pyramid_webpack#4]
I'm trying to follow the 'getting started' guide in your documentation, but I seem to be running into a few issues.

The first was an error stating that json.load() needs a string, not bytes. 

Fixed by replacing line 130 and 131 with:

     with self.stats_file.open() as f:
          return json.loads(f.read().decode('utf-8'))

However, now when I go to render the url:

        {% webpack 'main' %}
           {{ ASSET.url }}
        {% endwebpack %}

I'm getting an error: `jinja2.exceptions.UndefinedError: parameter 'ASSET' was not provided`

I've been stepping through the code and I can't seem to find the issue. Stepping through,  `caller(a) for a in ...` appears to be passing in the correct argument, and that argument exists all the way until the actual template is evaluated...

**Comment by stevearc** [comment]
This was due to an incompatibility with the Jinja2 0.9 release. Should be fixed in 0.1.2
